server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki-server:3100/loki/api/v1/push

scrape_configs:
- job_name: srv-mon
  static_configs:
  - targets:
      - localhost
    labels:
      job: server-logs
      __path__: /var/log/*log